[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "manufacturing"
version = "0.1.0"
dependencies = [
    "ortools==9.14.6206",
    "matplotlib==3.10.6",
    "plotly==6.2.0",
    "kaleido==0.1.0",
    "pandas==2.3.3",
    "dataclasses-json==0.6.7",
    "fastapi[standard-no-fastapi-cloud-cli]==0.119.0"
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["saved_plots*"]

[project.optional-dependencies]
test = [
    "pytest",
    "requests"
]