
name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install package and dependencies 
        run: |
          python3 -m pip install .[test]
      - name: Run solver tests
        run: |
          python -m pytest -v ./tests/test_solver.py
      - name: Run API tests
        run: |
          python server.py &
          SERVER_PID=$!
          sleep 1
          python -m pytest -v ./tests/test_api.py
          kill $SERVER_PID
      - name: Client example test
        run: |
          python server.py &
          SERVER_PID=$!
          sleep 1
          python examples/client_example.py
          kill $SERVER_PID
